dc_name: DC1

spine:
  defaults:
    loopback_ipv4_pool: 10.1.0.0/24
    bgp_defaults:
      - 'distance bgp 150 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    bgp_as: "65100"
    # evpn_route_servers: [ dc2-spine1, dc2-spine2 ]
    evpn_role: none
  nodes:
    - name: "dc1-spine1"
      id: 1
      mgmt_ip: 192.168.0.11/24
      # serial_number: "SN-dc1-spine1"
    - name: "dc1-spine2"
      id: 2
      mgmt_ip: 192.168.0.12/24
      # serial_number: "SN-dc1-spine2"

l3leaf:
  defaults:
    virtual_router_mac_address: 00:11:22:33:44:55
    loopback_ipv4_pool: 10.1.0.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.1.1.0/24
    max_uplink_switches: 2
    uplink_switches: [ dc1-spine1, dc1-spine2 ]
    uplink_interfaces: [ Ethernet9, Ethernet10 ]
    uplink_ipv4_pool: 10.1.2.0/24
    mlag_interfaces: [ Ethernet11, Ethernet12 ]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    bgp_defaults:
      - 'distance bgp 150 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    # evpn_route_servers: [ dc1-spine1, dc1-spine2 ]
    evpn_route_servers: [ dc1-leaf1, dc1-leaf2 ]
    evpn_services_l2_only: false
    mlag_peer_ipv4_pool: 10.1.3.0/24
    mlag_peer_l3_ipv4_pool: 10.1.4.0/24
    evpn_role: client
  node_groups:
    - group: "dc1-leaf-pair1"
      bgp_as: "65101"
      evpn_role: server
      evpn_route_servers: [ dc2-leaf1, dc2-leaf2 ]
      filter:
        tenants: [ all ]
        tags: [ all ]
      nodes:
        - name: "dc1-leaf1"
          id: 1
          mgmt_ip: 192.168.0.13/24
          # serial_number: "SN-dc1-leaf1"
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: "dc1-leaf2"
          id: 2
          mgmt_ip: 192.168.0.14/24
          # serial_number: "SN-dc1-leaf2"
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: "dc1-leaf-pair2"
      bgp_as: "65102"
      filter:
        tenants: [ all ]
        tags: [ all ]
      nodes:
        - name: "dc1-leaf3"
          id: 3
          mgmt_ip: 192.168.0.15/24
          # serial_number: "SN-dc1-leaf3"
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: "dc1-leaf4"
          id: 4
          mgmt_ip: 192.168.0.16/24
          # serial_number: "SN-dc1-leaf4"
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
