dc_name: DC2

spine:
  defaults:
    loopback_ipv4_pool: 10.2.0.0/24
    bgp_defaults:
      - 'distance bgp 150 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    bgp_as: "65200"
    # evpn_route_servers: [ dc1-spine1, dc1-spine2 ]
    evpn_role: none
  nodes:
    - name: "dc2-spine1"
      id: 1
      mgmt_ip: 192.168.0.21/24
      # serial_number: "SN-dc2-spine1"
    - name: "dc2-spine2"
      id: 2
      mgmt_ip: 192.168.0.22/24
      # serial_number: "SN-dc2-spine2"

l3leaf:
  defaults:
    virtual_router_mac_address: 00:11:22:33:44:55
    loopback_ipv4_pool: 10.2.0.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.2.1.0/24
    max_uplink_switches: 2
    uplink_switches: [ dc2-spine1, dc2-spine2 ]
    uplink_interfaces: [ Ethernet9, Ethernet10 ]
    uplink_ipv4_pool: 10.2.2.0/24
    mlag_interfaces: [ Ethernet11, Ethernet12 ]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    bgp_defaults:
      - 'distance bgp 150 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    evpn_route_servers: [ dc2-leaf1, dc2-leaf2 ]
    evpn_role: client
    evpn_services_l2_only: false
    mlag_peer_ipv4_pool: 10.2.3.0/24
    mlag_peer_l3_ipv4_pool: 10.2.4.0/24
  node_groups:
    - group: "dc2-leaf-pair1"
      bgp_as: "65201"
      evpn_route_servers: [ dc1-leaf1, dc1-leaf2 ]
      evpn_role: server
      filter:
        tenants: [ all ]
        tags: [ all ]
      nodes:
        - name: "dc2-leaf1"
          id: 1
          mgmt_ip: 192.168.0.23/24
          # serial_number: "SN-dc2-leaf1"
          uplink_switch_interfaces: [ Ethernet1, Ethernet1 ]
        - name: "dc2-leaf2"
          id: 2
          mgmt_ip: 192.168.0.24/24
          # serial_number: "SN-dc2-leaf2"
          uplink_switch_interfaces: [ Ethernet2, Ethernet2 ]
    - group: "dc2-leaf-pair2"
      bgp_as: "65202"
      filter:
        tenants: [ all ]
        tags: [ all ]
      nodes:
        - name: "dc2-leaf3"
          id: 3
          mgmt_ip: 192.168.0.25/24
          # serial_number: "SN-dc2-leaf3"
          uplink_switch_interfaces: [ Ethernet3, Ethernet3 ]
        - name: "dc2-leaf4"
          id: 4
          mgmt_ip: 192.168.0.26/24
          # serial_number: "SN-dc2-leaf4"
          uplink_switch_interfaces: [ Ethernet4, Ethernet4 ]
