servers:
#
# MLAG
#

  - name: "SERVER_GW2"
    adapters:
    - mode: access
      port_channel:
        description: SERVER_GW2
        mode: active
      endpoint_ports:
      - Eth0
      - Eth1
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - dc2-leaf1
      - dc2-leaf2 
      spanning_tree_portfast: edge
      vlans: '100'

  - name: "SERVER2-1"
    adapters:
    - mode: access
      port_channel:
        description: SERVER2-1
        mode: active
      endpoint_ports:
      - Eth0
      - Eth1
      switch_ports:
      - Ethernet2
      - Ethernet2
      switches:
      - dc2-leaf1
      - dc2-leaf2 
      spanning_tree_portfast: edge
      vlans: '10'

  - name: "SERVER2-2"
    adapters:
    - mode: access
      port_channel:
        description: SERVER2-2
        mode: active
      endpoint_ports:
      - Eth0
      - Eth1
      switch_ports:
      - Ethernet1
      - Ethernet1
      switches:
      - dc2-leaf3
      - dc2-leaf4
      spanning_tree_portfast: edge
      vlans: '10'