---
  - hosts: all
    gather_facts: no
    tasks:
    - name: Add User
      eos_user:
        name: ansible
        nopassword: yes
        privilege: 15
        role: network-admin
        state: present
    - name: Add SSH key
      eos_user:
        name: ansible
        sshkey: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present