---
  - hosts: all
    gather_facts: no
    tasks: 

    - name: Create onboarding token for CVAAS
      eos_command:
        commands:
          - enable
          - configure
          - bash
          - echo "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhc2V0SUQiOjkwODE1LCJleHAiOjE3Mzg5Mzg2MjgsImtpZCI6IjQ0NzgwYzRjMjA0MTM3MmUiLCJuYmYiOjE3MzgzMzM4MjgsInJlZW5yb2xsRGV2aWNlcyI6WyIqIl19.LWapL6Vq5SArcQ58lsTXRN5Y3BXSDAkRaTvujJ2kwA9lGtuIZDKBXHgnZB64lH4E5f03bcK3b51ywYgDd1SrPB3yLXmTZ96jCXQuY-LgmP6KIaXSIWZEGZg7IaO3DRa-XiI-nJIhXdgcXMDZoRbZLtyUI-Z21ogTKMdQvIBc6gciagUQCnr_KS_CxVZswHHKyidn3mZyfPo-ZdLhP0JVJ_bWvyAJJ0sBVKoeX2GPXwflMISj0Jpns1M-uD8UZbg7VHfKxPY_RGvQ5_f27mHgggMk-UiTIYgG-x2iVVpIDhb239XCUnuAzumOpXbm0rcEtmWdvfEz2br-PbeFb9w4RQ" > /mnt/flash/cv-onboarding-token
          - exit
          - exit

    - name: Provision TerminAttr for CVAAS
      template:
       src: "{{lookup('env','PWD')}}/templates/terminattr_cvaas.j2"
       dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_terminattr_cvaas.cfg"

    - name: Upload config
      eos_config:
        src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_terminattr_cvaas.cfg"

    - name: Restart terminattr
      eos_command:
        commands:
          - enable
          - configure
          - daemon TerminAttr
          - shutdown
          - no shutdown
          - exit